include:
  - project: acc-co/devops/python/acc-py-gitlab-ci-templates
    file: v2/python.gitlab-ci.yml

variables:
  PY_VERSION: "3.9"
  ACC_PY_BASE_IMAGE_NAME: "acc-py_cc7_openjdk11_ci"
  ACC_PY_BASE_IMAGE_TAG: "2021.12"
  project_name: "sps_app_hysteresis"

build_wheel:
  extends: .acc_py_build_wheel

#test_dev:
#  extends: .acc_py_dev_test
#  image: registry.cern.ch/acc/${ACC_PY_BASE_IMAGE_NAME}:${ACC_PY_BASE_IMAGE_TAG}

test_wheel:
  extends: .acc_py_wheel_test

build_sdist:
  extends: .acc_py_build_sdist

build_docs_on_tag:
 extends: .acc_py_build_docs_on_tag

publish_on_tag:
 extends: .acc_py_publish
